# Generated by Django 3.2.9 on 2021-11-12 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.TextField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('device', models.TextField(max_length=50)),
                ('device_serial_number', models.TextField(max_length=36)),
                ('device_timestamp', models.DateTimeField()),
                ('device_record_type', models.IntegerField()),
                ('glucose_value', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='una_app.user')),
            ],
            options={
                'unique_together': {('device_timestamp', 'user')},
            },
        ),
    ]
